AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - gemfiles/*
    - bin/*

Style/AccessorGrouping:
  EnforcedStyle: separated

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
